SQLALCHEMY_DATABASE_URI = 'sqlite:///sql_lite.db'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRETE_KEY = 'secret'
PROJECT_STORAGE_DIRECTORY = './storage'
DEBUG = True
AUTH_TOKEN = 'filloutinprod'
CUCKOO_API_URL = 'http://localhost:8090'
CUCKOO_API_TOKEN = '5Ql0ClpOzM9oot53daAIvA'
