name: gh pages
on:
  push:
    branches:
      - main
jobs:
  pages:
    name: pages
    runs-on: ubuntu-latest
    container: python:3.8-alpine3.12
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: execute py script # run the run.py to get the latest data
        run: |
          cd .github
          python --version
          pip install jinja2
          python compile-docs.py
