name: gh pages
on:
  push:
    branches:
      - main
jobs:
  pages:
    name: pages
    runs-on: ubuntu-latest
    container: python:3.8-alpine3.12
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: execute py script # run the run.py to get the latest data
        run: |
          cd .github
          python --version
          git --version
          pip install jinja2
          python compile-docs.py
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .github/out # The folder the action should deploy.
